# Generated by Django 4.1 on 2022-08-28 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='titile',
            new_name='title',
        ),
    ]
